export const RBAC_PERMISSIONS = {
  SUPER_ADMIN: {
    customers: ['create', 'read', 'update', 'delete', 'export', 'admin'],
    deals: ['create', 'read', 'update', 'delete', 'export', 'admin'],
    helpdesk: ['create', 'read', 'update', 'delete', 'export', 'admin'],
    billing: ['create', 'read', 'update', 'delete', 'export', 'admin'],
    analytics: ['read', 'export', 'admin'],
    audit: ['read', 'export', 'admin'],
    users: ['create', 'read', 'update', 'delete', 'admin'],
    settings: ['read', 'update', 'admin'],
  },
  ADMIN: {
    customers: ['create', 'read', 'update', 'delete', 'export'],
    deals: ['create', 'read', 'update', 'delete', 'export'],
    helpdesk: ['create', 'read', 'update', 'delete', 'export'],
    billing: ['create', 'read', 'update', 'delete', 'export'],
    analytics: ['read', 'export'],
    audit: ['read', 'export'],
    users: ['create', 'read', 'update'],
    settings: ['read', 'update'],
  },
  SALES_MANAGER: {
    customers: ['create', 'read', 'update', 'export'],
    deals: ['create', 'read', 'update', 'delete', 'export'],
    helpdesk: ['read'],
    billing: ['create', 'read', 'update'],
    analytics: ['read', 'export'],
    audit: ['read'],
    users: ['read'],
    settings: ['read'],
  },
  SALES_AGENT: {
    customers: ['create', 'read', 'update'],
    deals: ['create', 'read', 'update'],
    helpdesk: ['create', 'read'],
    billing: ['read'],
    analytics: ['read'],
    audit: [],
    users: ['read'],
    settings: [],
  },
  SUPPORT_AGENT: {
    customers: ['read', 'update'],
    deals: ['read'],
    helpdesk: ['create', 'read', 'update', 'delete'],
    billing: ['read'],
    analytics: ['read'],
    audit: [],
    users: ['read'],
    settings: [],
  },
  COMPLIANCE_AUDITOR: {
    customers: ['read'],
    deals: ['read'],
    helpdesk: ['read'],
    billing: ['read'],
    analytics: ['read'],
    audit: ['read', 'export'],
    users: ['read'],
    settings: ['read'],
  },
} as const;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;
