export interface EnterpriseReportDefinition {
  reportId: string;
  title: string;
  category: 'REVENUE' | 'SALES_PIPELINE' | 'CUSTOMER_HEALTH' | 'HELPDESK_SLA' | 'AUDIT_SECURITY';
  description: string;
  refreshFrequency: 'REAL_TIME' | 'HOURLY' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  sqlQueryTemplate: string;
  visualChartType: 'AREA' | 'BAR' | 'FUNNEL' | 'HEATMAP' | 'GAUGE' | 'DATA_TABLE';
  supportedExportFormats: string[];
}

export const ENTERPRISE_REPORT_CATALOG: EnterpriseReportDefinition[] = [
  {
    reportId: 'REP_DEF_001',
    title: 'Enterprise Analytics Blueprint #001 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'BAR',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_002',
    title: 'Enterprise Analytics Blueprint #002 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'FUNNEL',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_003',
    title: 'Enterprise Analytics Blueprint #003 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'HEATMAP',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_004',
    title: 'Enterprise Analytics Blueprint #004 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'GAUGE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_005',
    title: 'Enterprise Analytics Blueprint #005 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'DATA_TABLE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_006',
    title: 'Enterprise Analytics Blueprint #006 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'AREA',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_007',
    title: 'Enterprise Analytics Blueprint #007 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'BAR',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_008',
    title: 'Enterprise Analytics Blueprint #008 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'FUNNEL',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_009',
    title: 'Enterprise Analytics Blueprint #009 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'HEATMAP',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_010',
    title: 'Enterprise Analytics Blueprint #010 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'GAUGE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_011',
    title: 'Enterprise Analytics Blueprint #011 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'DATA_TABLE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_012',
    title: 'Enterprise Analytics Blueprint #012 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'AREA',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_013',
    title: 'Enterprise Analytics Blueprint #013 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'BAR',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_014',
    title: 'Enterprise Analytics Blueprint #014 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'FUNNEL',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_015',
    title: 'Enterprise Analytics Blueprint #015 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'HEATMAP',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_016',
    title: 'Enterprise Analytics Blueprint #016 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'GAUGE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_017',
    title: 'Enterprise Analytics Blueprint #017 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'DATA_TABLE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_018',
    title: 'Enterprise Analytics Blueprint #018 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'AREA',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_019',
    title: 'Enterprise Analytics Blueprint #019 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'BAR',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_020',
    title: 'Enterprise Analytics Blueprint #020 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'FUNNEL',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_021',
    title: 'Enterprise Analytics Blueprint #021 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'HEATMAP',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_022',
    title: 'Enterprise Analytics Blueprint #022 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'GAUGE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_023',
    title: 'Enterprise Analytics Blueprint #023 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'DATA_TABLE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_024',
    title: 'Enterprise Analytics Blueprint #024 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'AREA',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_025',
    title: 'Enterprise Analytics Blueprint #025 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'BAR',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_026',
    title: 'Enterprise Analytics Blueprint #026 - Sales Pipeline Telemetry',
    category: 'SALES_PIPELINE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'FUNNEL',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_027',
    title: 'Enterprise Analytics Blueprint #027 - Customer Health Telemetry',
    category: 'CUSTOMER_HEALTH',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'HEATMAP',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_028',
    title: 'Enterprise Analytics Blueprint #028 - Helpdesk Sla Telemetry',
    category: 'HELPDESK_SLA',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'GAUGE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_029',
    title: 'Enterprise Analytics Blueprint #029 - Audit Security Telemetry',
    category: 'AUDIT_SECURITY',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'DATA_TABLE',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
  {
    reportId: 'REP_DEF_030',
    title: 'Enterprise Analytics Blueprint #030 - Revenue Telemetry',
    category: 'REVENUE',
    description: 'Calculates high-precision aggregation matrices, moving averages, and variance bounds for executive reporting.',
    refreshFrequency: 'DAILY',
    sqlQueryTemplate: 'SELECT tenant_id, strftime("%Y-%m", created_at) as period, COUNT(*) as count, SUM(deal_value) as total_val FROM deals WHERE tenant_id = :tenantId GROUP BY period ORDER BY period DESC',
    visualChartType: 'AREA',
    supportedExportFormats: ['CSV', 'EXCEL_XLSX', 'JSON', 'PDF_REPORT'],
  },
];
