-- Migration 002: Customer 360 & Contact Hierarchy
CREATE TABLE IF NOT EXISTS customer_organizations (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    account_number VARCHAR(64) UNIQUE NOT NULL,
    legal_name VARCHAR(255) NOT NULL,
    trading_name VARCHAR(255),
    registration_number VARCHAR(100),
    tax_id VARCHAR(100),
    industry VARCHAR(100),
    sector VARCHAR(100),
    employee_count_bracket VARCHAR(50),
    annual_revenue_usd NUMERIC(18, 2) DEFAULT 0.00,
    lifecycle_stage VARCHAR(50) DEFAULT 'LEAD',
    lead_score INTEGER DEFAULT 0,
    health_score INTEGER DEFAULT 100,
    churn_probability_percent NUMERIC(5, 2) DEFAULT 0.00,
    assigned_account_executive_id VARCHAR(64),
    assigned_customer_success_manager_id VARCHAR(64),
    billing_currency VARCHAR(10) DEFAULT 'USD',
    payment_terms_days INTEGER DEFAULT 30,
    website_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    is_vip BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    custom_attributes_json TEXT DEFAULT '{}',
    tags_array TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_contact_persons (
    id VARCHAR(64) PRIMARY KEY,
    organization_id VARCHAR(64) NOT NULL REFERENCES customer_organizations(id) ON DELETE CASCADE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    job_title VARCHAR(150),
    department VARCHAR(100),
    email_address VARCHAR(255) NOT NULL,
    phone_direct VARCHAR(50),
    phone_mobile VARCHAR(50),
    is_primary_contact BOOLEAN DEFAULT FALSE,
    is_billing_contact BOOLEAN DEFAULT FALSE,
    is_technical_contact BOOLEAN DEFAULT FALSE,
    decision_making_role VARCHAR(50),
    communication_channel_preference VARCHAR(50) DEFAULT 'EMAIL',
    do_not_call BOOLEAN DEFAULT FALSE,
    do_not_email BOOLEAN DEFAULT FALSE,
    notes_narrative TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
